HomeTask2/еуые/Controllers/AdressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using еуые.Services;
using еуые.Models;
using System.Web.Mvc;

namespace еуые.Controllers
{
    public class AdressController : Controller
    {
        private Service userServive;

        public AdressController()
        {
            userServive = new Service();
        }

        public ActionResult Index(string searchId)
        {
            ViewBag.Check = 0;
            if (searchId != null)
            {
                ViewBag.Check = 1;
                try
                {
                    int indx = Convert.ToInt32(searchId);
                    Adress adress = (userServive.GetUsers()).Where(a => a.adress.Id == indx).Select(a => a.adress).FirstOrDefault();
                    ViewBag.UserName = (userServive.GetUsers()).Where(a => a.adress.Id == indx).Select(a => a.Name).FirstOrDefault();
                    return View(adress);
                }
                catch
                {
                    ViewBag.Check = 3;
                    return View();
                }
            }
            return View();
        }

    }
}

HomeTask2/еуые/Controllers/AllUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using еуые.Services;
using еуые.BuisnessLogic;
using еуые.Models;
using System.Web;
using System.Web.Mvc;

namespace еуые.Controllers
{
    public class AllUsersController : Controller
    {
        private Service userServive;

        public AllUsersController()
        {
            userServive = new Service();

        }
        // GET: AllUsers
        public ActionResult Index()
        {
            List<User> someUser = userServive.GetUsers();
            return View(someUser);
        }
    }
}

HomeTask2/еуые/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using еуые.Services;
using еуые.Models;
using System.Web.Mvc;

namespace еуые.Controllers
{
    public class PostController : Controller
    {
        private Service userServive;

        public PostController()
        {
            userServive = new Service();
        }
        public ActionResult Index(string searchId)
        {
            ViewBag.Check = 0;
            if (searchId != null)
            {
                ViewBag.Check = 1;
                try
                {
                    int indx = Convert.ToInt32(searchId);
                    var PostList = (userServive.GetUsers()).SelectMany(p => p.posts);
                    Post post = PostList.Where(p => p.Id == indx).Select(p=> p).FirstOrDefault();
                    ViewBag.UserName = (userServive.GetUsers()).Where(u => u.Id == post.UserId).Select(u => u.Name).FirstOrDefault();
                    return View(post);
                }
                catch
                {
                    ViewBag.Check = 3;
                    return View();
                }
            }
            return View();
        }
    }
}

HomeTask2/еуые/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using еуые.Models;
using еуые.Services;
using System.Web.Mvc;

namespace еуые.Controllers
{
    public class TodoController : Controller
    {
        // GET: Todo
        private Service userServive;

        public TodoController()
        {
            userServive = new Service();
        }
        public ActionResult Index(string searchId)
        {
            ViewBag.Check = 0;
            if (searchId != null)
            {      
                ViewBag.Check = 1;
                try
                {
                    int indx = Convert.ToInt32(searchId);
                    var TodoList = (userServive.GetUsers()).SelectMany(a => a.todos);
                    Todo todo = TodoList.Where(t => t.Id == indx).Select(t => t).FirstOrDefault();
                    ViewBag.UserName = (userServive.GetUsers()).Where(u => u.Id == todo.UserId).Select(u => u.Name).FirstOrDefault();
                    if (todo.ISComplete)
                    {
                        ViewBag.Color ="#90ee90";
                        ViewBag.Status = "Completed";
                    }
                    else
                    {
                        ViewBag.Color = "#E77471";
                        ViewBag.Status = "Uncomplet";
                    }
                    return View(todo);
                }
                catch
                {
                    ViewBag.Check = 3;
                    return View();
                }
            }
            return View();
        }
    }
}

HomeTask2/еуые/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using еуые.Services;
using еуые.Models;

namespace еуые.Controllers
{
    public class UserController : Controller
    {
        private Service userServive;

        public UserController()
        {
            userServive = new Service();
        }
        public ActionResult Index(string searchId)
        {
            ViewBag.Check = 0;
            if (searchId != null)
            {
                ViewBag.Check = 1;
                try
                {
                    int indx = Convert.ToInt32(searchId);
                    User user = (userServive.GetUsers()).Where(u => u.Id == indx).Select(u => u).FirstOrDefault();
                    ViewBag.AdressName = user.adress.Country;
                    ViewBag.AdressId = user.adress.Id;
                    return View(user);
                }
                catch
                {
                    ViewBag.Check = 3;
                    return View();
                }
            }
            return View();
        }
    }
}

HomeTask2/еуые/Views/AllUsers/Index.cshtml
@model  List<еуые.Models.User>
@{
    ViewBag.Title = "All users";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string ai = "";
    string an = "";
    string ui = "";
    string un = "";
}


<h3>Here is all the data gathered in one place</h3>

@foreach (var u in @Model)
{
    <div style="border:1px solid black">
        <table border="1">
            <tr>
                <td align="center">Avatar</td>
                <td align="center">Name</td>
                <td align="center">Id</td>
                <td align="center">Adress</td>
                <td align="center">Count of created posts</td>
                <td align="center">Count of todos</td>
            </tr>
            <tr>
                <td align="center"><img src="@u.Avatar" alt="@u.Name" /></td>

                @{
                    ui = Convert.ToString(u.Id);
                    un = Convert.ToString(u.Name);
                    try
                    {
                        ai = Convert.ToString(u.adress.Id);
                        an = Convert.ToString(u.adress.Country);
                    }
                    catch
                    {
                        ai = "Error";
                        an = "Error";
                    }

                }
                <td align="center">@u.Name</td>
                <td align="center">@Html.ActionLink(ui, "Index", "User", new { searchId = ui }, null)</td>
                <td align="center">@Html.ActionLink(an, "Index", "Adress", new { searchId = ai }, null)</td>
                <td align="center">@u.posts.Count</td>
                <td align="center">@u.todos.Count</td>
            </tr>
        </table>




        <div class="accordion">
            @{int uii = u.Id + 1;  int uiii = -1* (u.Id + 1); }
            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#@uii" aria-expanded="false" aria-controls="collapseTwo">
                            List of his posts with comments
                        </button>
                    </h5>
                </div>

                <div id="@uii" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                    <div class="card-body">
                        @if (@u.posts.Count > 0)
                        {
                            <ul>
                                @foreach (var p in @u.posts)
                                {
                                    <li>
                                        @Html.ActionLink(p.Body, "Index", "Post", new { searchId = p.Id }, null)<ul>
                                        @foreach (var c in p.comments)
                                        {
                                            <li>@Html.ActionLink(c.Body, "Index", "Comment", new { searchId = c.Id }, null)</li>
                                        }
                                    </ul>
                                </li>
                                }
                            </ul>
                        }
                        else
                        {
                            <strong>User has not created any post yet :( </strong>
                        }
                    </div>
                </div>
            </div>
        </div>

        <div class="accordion">
            <div class="card">
                <div class="card-header" id="headingThree">
                    <h5 class="mb-0">
                        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#@uiii" aria-expanded="false" aria-controls="collapseTwo">
                            List of his Todos
                        </button>
                    </h5>
                </div>
                <div id="@uiii" class="collapse" aria-labelledby="headingthree" data-parent="#accordion">
                    <div class="card-body">
                        @if (@u.todos.Count > 0)
                        {
                            <ul>
                                @foreach (var t in u.todos)
                                {
                                    <li>@Html.ActionLink(t.Name, "Index", "Todo", new { searchId = t.Id }, null)</li>
                                }
                            </ul>
                        }
                        else
                        {
                            <strong>User has not todo list yet :( </strong>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
     <br />
}