HomeTask2/еуые/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using еуые.Services;
using еуые.Models;

namespace еуые.Controllers
{
    public class CommentController : Controller
    {
        private Service userServive;
  
        public CommentController()
        {
            userServive = new Service();
        }

        public ActionResult Index(string searchId)
        {
            ViewBag.Check = 0;
            if (searchId != null)
            {
                ViewBag.Check = 1;
                try
                {
                    int indx = Convert.ToInt32(searchId);
                    var PostList = (userServive.GetUsers()).SelectMany(p => p.posts);
                    var CommentList = PostList.SelectMany(a => a.comments);
                    Comment comment = CommentList.Where(c => c.Id == indx).Select(c => c).FirstOrDefault();
                    ViewBag.PostId = Convert.ToString(comment.PostId);
                    ViewBag.UserName = (userServive.GetUsers()).Where(u => u.Id == comment.UserId).Select(u => u.Name).FirstOrDefault();
                    return View(comment);
                }
                catch
                {
                    ViewBag.Check = 2;
                    return View();
                }
            }
            return View();
        }
    }
}

HomeTask2/еуые/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using еуые.Services;
using еуые.Models;
using System.Web.Mvc;

namespace еуые.Controllers
{
    public class PostController : Controller
    {
        private Service userServive;

        public PostController()
        {
            userServive = new Service();
        }
        public ActionResult Index(string searchId)
        {
            ViewBag.Check = 0;
            if (searchId != null)
            {
                ViewBag.Check = 1;
                try
                {
                    int indx = Convert.ToInt32(searchId);
                    var PostList = (userServive.GetUsers()).SelectMany(p => p.posts);
                    Post post = PostList.Where(p => p.Id == indx).Select(p=> p).FirstOrDefault();
                    ViewBag.UserName = (userServive.GetUsers()).Where(u => u.Id == post.UserId).Select(u => u.Name).FirstOrDefault();
                    return View(post);
                }
                catch
                {
                    ViewBag.Check = 3;
                    return View();
                }
            }
            return View();
        }
    }
}

HomeTask2/еуые/Controllers/Task6Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using еуые.Services;
using еуые.BuisnessLogic;
using еуые.Models;
using System.Web.Mvc;

namespace еуые.Controllers
{
    public class Task6Controller : Controller
    {
        // GET: Task6
        private Service userServive;

        public Task6Controller()
        {
            userServive = new Service();
        }

        public ActionResult Index(string searchId)
        {
            ViewBag.Check = 0;
            if (searchId != null)
            {
                ViewBag.Check = 1;
                try
                {
                    int indx = Convert.ToInt32(searchId);
                    StructureForTask6 result = BuisnessLogic.Tasks.Task6(indx);
                    return View(result);
                }
                catch
                {
                    ViewBag.Check = 2;
                    return View();
                }
            }
            return View();
        }
    }
}

HomeTask2/еуые/Views/Task6/Index.cshtml
@model  еуые.Models.StructureForTask6
@{
    ViewBag.Title = "Task6";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
}


@if (@ViewBag.Check == 0)
{
    <h2>Task6</h2>
    <form method="get" asp-controller="Task6Controller" asp-action="Index">
        <div>
            <label for="searchId">Search the task result info by post id</label>
            <input type="text" name="searchId" placeholder="Input post id here." title="Id need to be from 1 to 100" />
            <input type="submit" value="Search">
        </div>
    </form>
}
else if (@ViewBag.Check == 1)
{
    <h2>Result of the task</h2>
    string pi = Convert.ToString(@Model.Post.Id);
    <div>Click on title to learn more about the post:  @Html.ActionLink(Model.Post.Title, "Index", "Post", new { searchId = pi }, null)</div>

    <div>
        The body of longest comment of the post is
        @if (@Model.LongestComment != null)
        {
            string lcid = Convert.ToString(Model.LongestComment.Id);
            <strong>@Html.ActionLink(Model.LongestComment.Body, "Index", "Comment", new { searchId = lcid }, null)</strong>
        }
        else
        {
            <strong>There is no such comment</strong>
        }
    </div>
    <div>
        The body of the coolest comment of this post is
        @if (@Model.CoolestComment != null)
        {
            string lcid = Convert.ToString(Model.CoolestComment.Id);
            <strong>@Html.ActionLink(Model.CoolestComment.Body, "Index", "Comment", new { searchId = lcid }, null)</strong>
        }
        else
        {
            <strong>There is no such comment</strong>
        }
    </div>

    if (Model.Checker == true)
    {
        <div>
            The count of comments under the post which has 0 likes or body length < 80
            <strong>@Model.SpecifiedComment</strong>
        </div>
    }
    else
    {
        <div>Post does not fit the condition</div>
    }
    <br/>
    <br />
    <h2>Try again</h2>
    <form method="get" asp-controller="Task6Controller" asp-action="Index">
        <div>
            <label for="searchId">Search the task result info by post id</label>
            <input type="text" name="searchId" placeholder="Input post id here." title="Id need to be from 1 to 100" />
            <input type="submit" value="Search">
        </div>
    </form>
}
else
{
    <h2> Error </h2>
    <div> Please enter the correct data</div>
    <form method="get" asp-controller="Task6Controller" asp-action="Index">
        <div>
            <label for="searchId">Search the task result info by post id</label>
            <input type="text" name="searchId" placeholder="Input post id here." title="Id need to be from 1 to 100" />
            <input type="submit" value="Search">
        </div>
    </form>
}
